from enum import IntEnum, auto 
from ...build import cffi

class Key(IntEnum):
    NULL = 0
    ZERO = auto()
    ONE = auto()
    TWO = auto()
    THREE = auto()
    FOUR = auto()
    FIVE = auto()
    SIX = auto()
    SEVEN = auto()
    EIGHT = auto()
    NINE = auto()
    A = auto()
    B = auto()
    C = auto()
    D = auto()
    E = auto()
    F = auto()
    G = auto()
    H = auto()
    I = auto()
    J = auto()
    K = auto()
    L = auto()
    M = auto()
    N = auto()
    O = auto()
    P = auto()
    Q = auto()
    R = auto()
    S = auto()
    T = auto()
    U = auto()
    V = auto()
    W = auto()
    X = auto()
    Y = auto()
    Z = auto()
    UP = auto()
    DOWN = auto()
    LEFT = auto()
    RIGHT = auto()
    SPACE = auto()
    ENTER = auto()
    ESCAPE = auto()
    TAB = auto()
    BACKSPACE = auto()
    INSERT = auto()
    DELETE = auto()
    HOME = auto()
    END = auto()
    PAGE_UP = auto()
    PAGE_DOWN = auto()
    F1 = auto()
    F2 = auto()
    F3 = auto()
    F4 = auto()
    F5 = auto()
    F6 = auto()
    F7 = auto()
    F8 = auto()
    F9 = auto()
    F10 = auto()
    F11 = auto()
    F12 = auto()
    LEFT_SHIFT = auto()
    RIGHT_SHIFT = auto()
    LEFT_CONTROL = auto()
    RIGHT_CONTROL = auto()
    LEFT_ALT = auto()
    RIGHT_ALT = auto()
    LEFT_SUPER = auto()
    RIGHT_SUPER = auto()
    CAPS_LOCK = auto()
    SCROLL_LOCK = auto()
    NUM_LOCK = auto()
    APOSTROPHE = auto()
    COMMA = auto()
    MINUS = auto()
    PERIOD = auto()
    SLASH = auto()
    SEMICOLON = auto()
    EQUAL = auto()
    LEFT_BRACKET = auto()
    BACKSLASH = auto()
    RIGHT_BRACKET = auto()
    GRAVE = auto()
    NUMBER = auto()

key_to_cffi = {
    key: getattr(cffi.lib, f"NX_KEY_{key.name}") 
    for key in Key
}

cffi_to_key = {
    i: k 
    for k, i in key_to_cffi.items()
}