import pygame
from ..states.key import Key

PYGAME_TO_KEY: dict[int, Key] = {
    pygame.K_a: Key.A,
    pygame.K_b: Key.B,
    pygame.K_c: Key.C,
    pygame.K_d: Key.D,
    pygame.K_e: Key.E,
    pygame.K_f: Key.F,
    pygame.K_g: Key.G,
    pygame.K_h: Key.H,
    pygame.K_i: Key.I,
    pygame.K_j: Key.J,
    pygame.K_k: Key.K,
    pygame.K_l: Key.L,
    pygame.K_m: Key.M,
    pygame.K_n: Key.N,
    pygame.K_o: Key.O,
    pygame.K_p: Key.P,
    pygame.K_q: Key.Q,
    pygame.K_r: Key.R,
    pygame.K_s: Key.S,
    pygame.K_t: Key.T,
    pygame.K_u: Key.U,
    pygame.K_v: Key.V,
    pygame.K_w: Key.W,
    pygame.K_x: Key.X,
    pygame.K_y: Key.Y,
    pygame.K_z: Key.Z,
    pygame.K_0: Key.K_0,
    pygame.K_1: Key.K_1,
    pygame.K_2: Key.K_2,
    pygame.K_3: Key.K_3,
    pygame.K_4: Key.K_4,
    pygame.K_5: Key.K_5,
    pygame.K_6: Key.K_6,
    pygame.K_7: Key.K_7,
    pygame.K_8: Key.K_8,
    pygame.K_9: Key.K_9,
    pygame.K_SPACE: Key.SPACE,
    pygame.K_RETURN: Key.ENTER,
    pygame.K_ESCAPE: Key.ESCAPE,
    pygame.K_TAB: Key.TAB,
    pygame.K_BACKSPACE: Key.BACKSPACE,
    pygame.K_DELETE: Key.DELETE,
    pygame.K_LEFT: Key.LEFT,
    pygame.K_RIGHT: Key.RIGHT,
    pygame.K_UP: Key.UP,
    pygame.K_DOWN: Key.DOWN,
    pygame.K_LSHIFT: Key.LSHIFT,
    pygame.K_RSHIFT: Key.RSHIFT,
    pygame.K_LCTRL: Key.LCTRL,
    pygame.K_RCTRL: Key.RCTRL,
    pygame.K_LALT: Key.LALT,
    pygame.K_RALT: Key.RALT,
    pygame.K_F1: Key.F1,
    pygame.K_F2: Key.F2,
    pygame.K_F3: Key.F3,
    pygame.K_F4: Key.F4,
    pygame.K_F5: Key.F5,
    pygame.K_F6: Key.F6,
    pygame.K_F7: Key.F7,
    pygame.K_F8: Key.F8,
    pygame.K_F9: Key.F9,
    pygame.K_F10: Key.F10,
    pygame.K_F11: Key.F11,
    pygame.K_F12: Key.F12,
}

KEY_TO_PYGAME: dict[Key, int] = {v: k for k, v in PYGAME_TO_KEY.items()}

def pygame_to_key(pg_key: int) -> Key | None:
    return PYGAME_TO_KEY.get(pg_key)

def key_to_pygame(key: Key) -> int | None:
    return KEY_TO_PYGAME.get(key)

